prompts = [
    "What happened today?",
    "What was the best thing that happened today?",
    "What was the worst thing that happened today?",
    "What was the most interesting thing you saw or heard today?",
    "What was the most challenging thing you faced today?",
    "What are you grateful for today?",
    "What did you learn today?",
    "What was the most fun thing you did today?",
    "What was the most surprising thing that happened today?",
    "What did you do today that you are proud of?",
    "What do you love most about your body, and why?",
    "What beliefs or messages about your body do you need to let go of in order to cultivate more self-love and acceptance?",
    "What activities or practices help you feel connected to and in tune with your body?",
    "How can you be more compassionate towards your body, especially when you're feeling self-critical or negative?",
    "What role does social media or the media in general play in shaping your body image, and how can you cultivate a more positive relationship with these sources of influence?",
    "What would it feel like to let go of the need to compare your body to others, and instead focus on your own unique strengths and beauty?",
    "What are some ways you can prioritize your physical health and well-being, without falling into the trap of diet culture or body shaming?",
    "How can you shift your focus from appearance-based goals (e.g. weight loss, achieving a certain body shape) to more holistic measures of health and wellness (e.g. energy levels, mood, strength, etc.)?",
    "What does it mean to truly embody self-love and body positivity, and how can you take small steps towards this every day?",
    "How can you cultivate a sense of appreciation and love for your body, even if it doesn't conform to societal ideals?",
    "What are some ways you can celebrate and care for your body, regardless of its shape or size?",
    "What does creativity mean to you?",
    "How do you get to use your creativity on a daily basis?",
    "What is one thing that you have always wanted to create, and what steps can you take to make it a reality?",
    "What is one place or environment that inspires your creativity, and how can you create more opportunities to be in that space?",
    "What are your passions and interests, and how can you incorporate them into your work or personal life?",
    "What is one small creative project that you can do today, and how can you make it unique to your personal style?",
    "What is one fear or obstacle that is holding you back creatively, and what can you do to overcome it?",
    "What is one thing that you can learn or experiment with in order to expand your creative skills and knowledge?",
    "What is one challenge or prompt that you can give yourself to push yourself creatively?",
    "What is one way you can creatively express gratitude, love, or appreciation for someone in your life?",
    "How can you challenge yourself to think outside of the box and embrace new and creative ideas?",
    "How can you surround yourself with people and environments that foster creativity and inspiration?",
    "What are some ways you can take time for yourself and recharge your batteries to cultivate creativity and inspiration?",
    "What are some hobbies or activities you can pursue to tap into your creativity and imagination?",
    "How can you incorporate more play and fun into your life to foster creativity and inspiration?",
    "What are some ways you can break out of your comfort zone and try new things to stimulate creativity and inspiration?",
    "How can you be more open-minded and receptive to new ideas and perspectives?",
    "What are some ways you can use technology and innovation to enhance your creativity and inspiration?",
    "How can you seek out new experiences and adventures to expand your horizons and inspire your creativity?",
    "How can you create a supportive and nurturing environment for your mind, body, and soul to encourage creativity and inspiration?",
    "How are you feeling today?",
    "How does your body feel today?",
    "What are you nervous or anxious about today?",
    "What actions can you take on each of the things that make you nervous or anxious?",
    "What are your top priorities for the day?",
    "What's something you can do to make today amazing?",
    "What did you learn today? How can you apply this knowledge in the future?",
    "What challenges did you face today? How did you overcome them? What can you learn from these experiences?",
    "What did you do today that brought you joy or fulfillment? How can you incorporate more of these activities into your daily routine?",
    "What was a moment of joy, delight, or contentment today?",
    "What was a small detail you noticed today?",
    "What made you smile today?",
    "Who did you connect with today, and how did it make you feel?",
    "What's one thing you accomplished today, no matter how small?",
    "What are you looking forward to tomorrow?",
    "What's something you're curious about right now?",
    "How did you take care of yourself today?",
    "What's a compliment you'd like to give yourself today?",
    "What boundary did you set or wish you had set today?",
    "What's something you'd like to forgive yourself for?",
    "What does rest and relaxation look like for you right now?",
    "What's a risk you're glad you took recently?",
    "What's a relationship in your life that you're grateful for?",
    "How have you grown or changed in the past month?",
    "What's a limiting belief you're ready to release?",
    "What does success mean to you right now?",
    "What are three words that describe how you want to feel?",
    "What's something you've been avoiding, and why?",
    "What would you do if you knew you couldn't fail?",
    "What does your ideal day look like from start to finish?",
    "What are you ready to welcome into your life?",
    "What energizes you and makes you feel alive?",
    "What drains your energy, and how can you protect yourself from it?",
    "What's a kind gesture you could do for yourself today?",
    "What's a dream you've put on hold, and what's one small step you could take towards it?",
    "What would your future self thank you for doing today?"
]